image:
  file: .gitpod.Dockerfile
tasks:
- command: julia --version
vscode:
  extensions:
    - julialang.language-julia
    - ms-azuretools.vscode-docker
    - ms-vscode.live-server
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true